name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print runner information
        run: |
          echo "This job is running on a self-hosted runner"
          echo "Runner name: ${{ runner.os }}"
          echo "Runner version: ${{ runner.runnerVersion }}"
